{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install ipywidgets\n",
    "%pip install tensorflow_datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"model_14\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " input_45 (InputLayer)       [(None, 96, 96, 1)]       0         \n",
      "                                                                 \n",
      " sequential_28 (Sequential)  (None, 2)                 18434     \n",
      "                                                                 \n",
      " sequential_29 (Sequential)  (None, 96, 96, 1)         27648     \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 46,082\n",
      "Trainable params: 46,082\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "758/760 [============================>.] - ETA: 0s - loss: 0.1520"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "in user code:\n\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1852, in test_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1836, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1824, in run_step  **\n        outputs = model.test_step(data)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1788, in test_step\n        y_pred = self(x, training=False)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Exception encountered when calling layer 'model_14' (type Functional).\n    \n    Input 0 of layer \"sequential_28\" is incompatible with the layer: expected shape=(None, 96, 96, 1), found shape=(96, 96, 1, 1)\n    \n    Call arguments received by layer 'model_14' (type Functional):\n      • inputs=tf.Tensor(shape=(96, 96, 1), dtype=float32)\n      • training=False\n      • mask=None\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[24], line 45\u001b[0m\n\u001b[0;32m     41\u001b[0m model\u001b[39m.\u001b[39mcompile(optimizer\u001b[39m=\u001b[39mtf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39moptimizers\u001b[39m.\u001b[39mAdam(), loss\u001b[39m=\u001b[39mtf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39mlosses\u001b[39m.\u001b[39mHuber())\n\u001b[0;32m     43\u001b[0m model\u001b[39m.\u001b[39msummary()\n\u001b[1;32m---> 45\u001b[0m model\u001b[39m.\u001b[39;49mfit(\n\u001b[0;32m     46\u001b[0m         ds_train\u001b[39m.\u001b[39;49mbatch(\u001b[39m32\u001b[39;49m),\n\u001b[0;32m     47\u001b[0m         epochs\u001b[39m=\u001b[39;49m\u001b[39m1\u001b[39;49m,\n\u001b[0;32m     48\u001b[0m         batch_size\u001b[39m=\u001b[39;49m\u001b[39m32\u001b[39;49m,\n\u001b[0;32m     49\u001b[0m         shuffle\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m     50\u001b[0m         validation_data\u001b[39m=\u001b[39;49mds_test,\n\u001b[0;32m     51\u001b[0m     )\n\u001b[0;32m     53\u001b[0m \u001b[39m# last_loss = float('inf')\u001b[39;00m\n\u001b[0;32m     54\u001b[0m \u001b[39m# last_val_loss = float('inf')\u001b[39;00m\n\u001b[0;32m     55\u001b[0m \u001b[39m# threshold = 0.8  # 20% improvement threshold\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     72\u001b[0m \u001b[39m#     else:\u001b[39;00m\n\u001b[0;32m     73\u001b[0m \u001b[39m#         break\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32m~\\AppData\\Local\\Temp\\__autograph_generated_filezxqogx6e.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__test_function\u001b[1;34m(iterator)\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     14\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m     retval_ \u001b[39m=\u001b[39m ag__\u001b[39m.\u001b[39mconverted_call(ag__\u001b[39m.\u001b[39mld(step_function), (ag__\u001b[39m.\u001b[39mld(\u001b[39mself\u001b[39m), ag__\u001b[39m.\u001b[39mld(iterator)), \u001b[39mNone\u001b[39;00m, fscope)\n\u001b[0;32m     16\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m     17\u001b[0m     do_return \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "\u001b[1;31mValueError\u001b[0m: in user code:\n\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1852, in test_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1836, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1824, in run_step  **\n        outputs = model.test_step(data)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\training.py\", line 1788, in test_step\n        y_pred = self(x, training=False)\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File \"c:\\Users\\Frederik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Exception encountered when calling layer 'model_14' (type Functional).\n    \n    Input 0 of layer \"sequential_28\" is incompatible with the layer: expected shape=(None, 96, 96, 1), found shape=(96, 96, 1, 1)\n    \n    Call arguments received by layer 'model_14' (type Functional):\n      • inputs=tf.Tensor(shape=(96, 96, 1), dtype=float32)\n      • training=False\n      • mask=None\n"
     ]
    }
   ],
   "source": [
    "import tensorflow_datasets as tfds\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "\n",
    "def preprocess(x, y):\n",
    "    x = tf.cast(x, tf.float32) / 255.0\n",
    "    return x, x\n",
    "\n",
    "(ds_train, ds_test), ds_info = tfds.load(\n",
    "    'smallnorb',\n",
    "    split=['train', 'test'],\n",
    "    shuffle_files=True,\n",
    "    as_supervised=True,\n",
    "    with_info=True,\n",
    ")\n",
    "\n",
    "ds_train = ds_train.map(preprocess)\n",
    "ds_test = ds_test.map(preprocess)\n",
    "\n",
    "input_shape = (96, 96, 1)\n",
    "encoding_dimensions = 2\n",
    "\n",
    "encoder = tf.keras.Sequential([\n",
    "    tf.keras.layers.Input(shape=input_shape),\n",
    "    tf.keras.layers.Flatten(),\n",
    "    tf.keras.layers.Dense(units=encoding_dimensions, activation=tf.keras.activations.relu)\n",
    "])\n",
    "\n",
    "decoder = tf.keras.Sequential([\n",
    "    tf.keras.layers.Input(shape=(encoding_dimensions,)),\n",
    "    tf.keras.layers.Dense(units=np.prod(input_shape), activation=tf.keras.activations.relu),\n",
    "    tf.keras.layers.Reshape(target_shape=input_shape)\n",
    "])\n",
    "\n",
    "input = tf.keras.layers.Input(shape=input_shape)\n",
    "\n",
    "output = decoder(encoder(input))\n",
    "\n",
    "model = tf.keras.Model(inputs=input, outputs=output)\n",
    "\n",
    "model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.Huber())\n",
    "\n",
    "model.summary()\n",
    "\n",
    "model.fit(\n",
    "        ds_train.batch(32),\n",
    "        epochs=1,\n",
    "        batch_size=32,\n",
    "        shuffle=True,\n",
    "        validation_data=ds_test,\n",
    "    )\n",
    "\n",
    "# last_loss = float('inf')\n",
    "# last_val_loss = float('inf')\n",
    "# threshold = 0.8  # 20% improvement threshold\n",
    "# patience = 10\n",
    "\n",
    "# while (patience > 0):\n",
    "#     patience -= 1\n",
    "#     history = model.fit(\n",
    "#         ds_train.batch(32),\n",
    "#         epochs=1,\n",
    "#         batch_size=32,\n",
    "#         shuffle=True,\n",
    "#         validation_data=ds_test,\n",
    "#     )\n",
    "#     loss = history.history['loss'][-1]\n",
    "#     val_loss = history.history['val_loss'][-1]\n",
    "#     if loss < last_loss * threshold or val_loss < last_val_loss * threshold:\n",
    "#         last_loss = loss\n",
    "#         last_val_loss = val_loss\n",
    "#     else:\n",
    "#         break\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import tensorflow_datasets as tfds\n",
    "\n",
    "test_samples = np.array([\n",
    "    image\n",
    "    for image, _ in tfds.as_numpy(ds_test.take(5))\n",
    "])\n",
    "\n",
    "encoded_samples = encoder.predict(test_samples)\n",
    "decoded_samples = decoder.predict(encoded_samples)\n",
    "\n",
    "n = len(test_samples)\n",
    "plt.figure(figsize=(n * 2, 4))\n",
    "for i in range(n):\n",
    "    # display original\n",
    "    ax = plt.subplot(2, n, i + 1)\n",
    "    plt.imshow(test_samples[i])\n",
    "    plt.title(\"original\")\n",
    "    plt.gray()\n",
    "    ax.get_xaxis().set_visible(False)\n",
    "    ax.get_yaxis().set_visible(False)\n",
    "\n",
    "    # display reconstruction\n",
    "    ax = plt.subplot(2, n, i + 1 + n)\n",
    "    plt.imshow(decoded_samples[i])\n",
    "    plt.title(\"decoded\")\n",
    "    plt.gray()\n",
    "    ax.get_xaxis().set_visible(False)\n",
    "    ax.get_yaxis().set_visible(False)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
